name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: pd4
    steps:
      - uses: actions/checkout@v4

      - name: Build with devbox
        run: devbox run build

      - name: Run unit tests
        run: devbox run  go test -v ./pkg

      - name: Run step integration tests
        run: dist/bloom test tests/integration/step/*/*/bloom.yaml

      - name: Run UI tests
        run: |
          cd tests/ui
          go test -v ./...

      - name: QEMU Disk Test
        run: |
          bash tests/e2e/qemu/qemu-disk-test.sh nvme-test-vm dist/bloom tests/e2e/test_case_1/bloom.yaml

      - name: Check Test Results
        run: |
          SUCCESS=$(yq '.overall_summary.success' nvme-test-vm-test-results.yaml)
          if [ "$SUCCESS" != "true" ]; then
            echo "❌ Tests failed - check nvme-test-vm-test-results.yaml for details"
            cat nvme-test-vm-test-results.yaml
            exit 1
          fi
          echo "✅ All tests passed"
