name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: pd4
    steps:
      - uses: actions/checkout@v4

      - name: Build with devbox
        run: devbox run build

      - name: Run step integration tests
        run: dist/bloom test integration_tests/step/*/*/bloom.yaml

      - name: QEMU Disk Test
        run: |
          bash .github/workflows/qemu-disk-test.sh nvme-test-vm dist/bloom /home/ubuntu/ci/bloom.yaml
